language: go
sudo: false
matrix:
  include:
  - go: 1.x
    env: LATEST=true
before_install:
- go get github.com/mitchellh/gox
install:
- 
script:
- go get -t -v ./...
- go test -v -race ./...
- if [ "${LATEST}" = "true" ]; then gox -os="linux darwin" -arch="amd64" -output="ice.."
  -verbose ./...; fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: DwQEWHC7qX9OXjnEHtOuSjXjL6z+8ipXPl3Angdhgh7o4VMY1VcxNs20DN7VtKZ72uzPX9tZsanaQa/fpH7B24MJXViJaFPmhzajNVyZjzHw5f+f1cbvqNeurDUS7L5mABBGc79kPPfouwwOXspxy69xlg5nhwWDHUpBFIZzep07rqqKTMzamqWCKDoHYDUXRnrQNBFhoUmgC6liOYtUDCZrP4wXtSAEh7kyfmN9z/GQUMh/r+V5n4FZVDzCHULJfMa10elLvx/Zg2h4enlbplBpop0C1DSQX/C8rz7ux5v1yMLghsMY6tlUZBcnXe8pj56clhGLDfxCpt261PSwXyUWkDA6BC6TeWyyJQ9q2siTib9bOVcwwxYiatcnMUasCjft3iF/k5c9gnKVzTfE+w8K1rKy72kKzPMIzeYvByGSURxmv/M13cF4vNhxinSh/jxO3Fw1mPj15KD5Y9KSC254ZFh8tz8Un5iCRvykHRuyxyvRZOe4ub/Y0Wrjb8HsWcR7LAYp8/Z90LP9Gg9zwlF048qkNTmgAeS2PsDHumyGinBhUi2wU07tImzKYop5L1iOFJDuebN62xQO63pDBfWBcctkfIDu0qItUm6Sk1fLq1zb32tOfZytX3hRkChtnSWGK4wbIga+DRbQHMT+ZwNBuAqDXPj36ZgJqI3JLFc=
  file:
  - ice.darwin.amd64
  - ice .linux.amd64
  on:
    repo: allenisalai/ice
    tags: true
    condition: "$LATEST = true"

